const MIT_RSS='https://scioperi.mit.gov.it/mit2/public/scioperi/rss';
function clean(v=''){return String(v).replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/\s+/g,' ').trim()}
function norm(v=''){return clean(v).toUpperCase()}
function parseDateIT(v){const m=String(v).match(/(\d{2})\/(\d{2})\/(\d{4})/);return m?`${m[3]}-${m[2]}-${m[1]}`:null}
function tag(block,name){const m=block.match(new RegExp(`<${name}>([\\s\\S]*?)<\\/${name}>`,'i'));return m?clean(m[1]):''}
function field(desc,label){const raw=String(desc).replace(/<!\[CDATA\[|\]\]>/g,'');const m=raw.match(new RegExp(`${label}:\\s*([\\s\\S]*?)(?:<br\\s*\\/?\\s*>|$)`,'i'));return m?clean(m[1]):''}
function isRelevant(x){const all=norm(`${x.sector} ${x.category} ${x.mode} ${x.notes||''}`),reg=norm(x.region),sector=norm(x.sector),geo=reg==='ITALIA'||reg==='PIEMONTE',excludedPiemonte=all.includes('ESCLUS')&&all.includes('PIEMONTE'),rail=sector.includes('FERROVIARIO')||(sector.includes('PLURISETTORIALE')&&all.includes('FERROVI')),tpl=sector.includes('TRASPORTO PUBBLICO LOCALE')&&geo&&(all.includes('GTT')||all.includes('TORINO')||norm(x.relevance)==='NAZIONALE');return geo&&!excludedPiemonte&&(rail||tpl)}
function kindOf(x){return norm(x.sector).includes('TRASPORTO PUBBLICO LOCALE')?'metro':'train'}
function parseRSS(xml){const items=[...String(xml).matchAll(/<item>([\s\S]*?)<\/item>/gi)],out=[];for(const m of items){const block=m[1],title=tag(block,'title'),descRaw=(block.match(/<description>([\s\S]*?)<\/description>/i)||[])[1]||'',start=(title.match(/Data inizio:\s*(\d{2}\/\d{2}\/\d{4})/i)||[])[1]||'',sector=field(descRaw,'Settore')||(title.match(/Settore:\s*(.*?)\s*-\s*Rilevanza:/i)||[])[1]||'',relevance=field(descRaw,'Rilevanza')||(title.match(/Rilevanza:\s*(.*?)\s*-\s*Regione:/i)||[])[1]||'',region=field(descRaw,'Regione')||(title.match(/Regione:\s*(.*?)\s*-\s*Provincia:/i)||[])[1]||'',province=field(descRaw,'Provincia')||(title.match(/Provincia:\s*(.*)$/i)||[])[1]||'',end=field(descRaw,'Data fine'),unions=field(descRaw,'Sindacati'),category=field(descRaw,'Categoria interessata'),mode=field(descRaw,'modalità'),proclaimed=field(descRaw,'Data proclamazione'),received=field(descRaw,'Data ricezione'),item={start,end,startISO:parseDateIT(start),endISO:parseDateIT(end),unions,sector,category,mode,relevance,region,province,proclaimed,received,notes:'',guid:tag(block,'guid')};if(isRelevant(item)){item.kind=kindOf(item);out.push(item)}}return out.sort((a,b)=>(a.startISO||'').localeCompare(b.startISO||''))}
function todayRome(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
module.exports=async function handler(req,res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Cache-Control','no-store, max-age=0');try{const r=await fetch(MIT_RSS,{headers:{Accept:'application/rss+xml,application/xml,text/xml,*/*','User-Agent':'RostaTravel/1.0'},cache:'no-store'});if(!r.ok)throw new Error(`MIT RSS HTTP ${r.status}`);const xml=await r.text(),today=todayRome(),strikes=parseRSS(xml).filter(x=>!x.endISO||x.endISO>=today).slice(0,8);return res.status(200).json({ok:true,checkedAt:new Date().toISOString(),source:'MIT - Osservatorio conflitti sindacali',protectedBands:{weekday:['06:00–09:00','18:00–21:00'],holiday:['07:00–10:00','18:00–21:00'],note:'Per il Regionale i servizi minimi sono individuati per numero di treno e orario effettivo di partenza: essere nella fascia non rende automaticamente garantito ogni treno.'},strikes})}catch(error){return res.status(502).json({ok:false,error:'Calendario scioperi temporaneamente non disponibile',detail:String(error?.message||error)})}};